palabrasFrecuentes3 = ['confidential',
 'Steve',
 # 'cost',
 # 'December',
 # '#####,',
 # 'Chris',
 # 'points',
 # 'plans',
 # 'earlier',
 # 'trying',
 # 'Natural',
 # 'talk',
 # 'Final',
 # 'weeks',
 # 'Attached',
 # 'meter',
 # 'due',
 # 'August',
 # 'several',
 # 'additional',
 # 'demand',
 # 'disclosure',
 # 'alias:',
 # "Sunday's",
 # '!!!unknown',
 # 'dbcaps97data',
 # 'chairman',
 # 'utilities',
 # 'called',
 # 'Content-Disposition:',
 # 'support',
 # 'largest',
 # 'copies',
 # 'through',
 # 'filed',
 # 'board',
 # 'term',
 # 'James',
 # 'transmission',
 # 'say',
 # 'filing',
 # 'cents',
 # 'utility',
 # 'california',
 # 'unit',
 # 'give',
 # 'draft',
 # 'investors',
 # 'traders',
 # 'given',
 # 'anyone',
 # 'meet',
 # 'Mr.',
 # 'around',
 # 'help',
 # 'Reserved.',
 # 'News',
 # 'Street',
 # 'cash',
 # 'Free',
 # 'Wall',
 # 'scheduled',
 # 'done',
 # 'week,',
 # 'keep',
 # 'FERC',
 # 'early',
 # 'Maggi,',
 # 'Michelle',
 # 'North',
 # 'she',
 # '1,',
 # 'plant',
 # 'p.m.',
 # 'questions.',
 # 'according',
 # '#',
 # 'rights',
 # 'research',
 # 'three',
 # 'quarter',
 # 'HourAhead',
 # 'louise',
 # 'variances',
 # "didn't",
 # 'year.',
 # '2',
 # 'detected.',
 # 'awarded.',
 # 'mark',
 # 'status',
 # 'make',
 # '0.00',
 # 'basis',
 # 'perform',
 # 'David',
 # 'file',
 # 'pay',
 # 'fell',
 # 'database',
 # 'bankruptcy',
 # 'needs',
 # 'close',
 # 'year,',
 # 'probably',
 # 'yards',
 # 'then',
 # '**********************************************************************',
 # 'while',
 # 'For',
 # 'February',
 # 'Commission',
 # 'ancillary',
 # '(c)',
 # 'related',
 # 'current',
 # 'cut',
 # 'rate',
 # 'Jeff',
 # 'QB',
 # 'available',
 # 'move',
 # 'where',
 # 'Rights',
 # 'merger',
 # '2001,',
 # 'asked',
 # 'reported',
 # 'Enron,',
 # 'By',
 # 'want',
 # 'point',
 # "company's",
 # 'business',
 # 'proposed',
 # 'thanks,',
 # 'deals',
 # 'provide',
 # 'now',
 # 'e-mail',
 # 'comments',
 # 'operation',
 # 'daily',
 # 'executive',
 # 'process',
 # 'partnerships',
 # "I'm",
 # 'analysts',
 # 'run',
 # 'people',
 # '2001.',
 # 'schedules',
 # 'team',
 # 'john',
 # 'Thanks',
 # 'value',
 # 'told',
 # 'analyst',
 # '!!!Unknown',
 # 'being',
 # 'regarding',
 # 'able',
 # 'York',
 # 'transactions',
 # 'Agent',
 # 'corp.',
 # 'request',
 # 'AACsAQAArAEAAKwBAACsAQAArAEAAKwBAACsAQAArAEAAKwBAACsAQAArAEAAKwBAACsAQAArAEA',
 # 'AQAArAEAAKwBAACsAQAArAEAAKwBAACsAQAArAEAAKwBAACsAQAArAEAAKwBAACsAQAArAEAAKwB',
 # 'continue',
 # 'firm',
 # 'RB',
 # 'you.',
 # 'September',
 # 'U.S.',
 # 'just',
 # 'AKwBAACsAQAArAEAAKwBAACsAQAArAEAAKwBAACsAQAArAEAAKwBAACsAQAArAEAAKwBAACsAQAA',
 # 'Company,',
 # 'changes',
 # 'well',
 # 'rAEAAKwBAACsAQAArAEAAKwBAACsAQAArAEAAKwBAACsAQAArAEAAKwBAACsAQAArAEAAKwBAACs',
 # 'likely',
 # 'look',
 # 'however,',
 # 'hour:',
 # 'Alias:',
 # 'dbCaps97Data',
 # 'As',
 # 'issue',
 # 'California',
 # 'Copyright',
 # 'until',
 # 'hIEUhIEUhIEUhIEUhIEUhIEUhIEUhIEUhIEUhIEUhIEUhIEUhIEUhIEUhIEUhIEUhIEUhIEUhIEU',
 # 'assets',
 # 'very',
 # 'another',
 # 'project',
 # 'Thank',
 # 'set',
 # 'rating',
 # 'markets',
 # 'But',
 # '*',
 # 'those',
 # 'contact',
 # 'agreement',
 # 'whether',
 # 'management',
 # 'over',
 # 'says',
 # 'Thanks,',
 # 'use',
 # 'expected',
 # 'received',
 # 'good',
 # 'put',
 # 'pipeline',
 # 'discuss',
 # 'sure',
 # 'both',
 # 'closed',
 # 'company,',
 # 'thanks',
 # 'conference',
 # 'already',
 # 'data',
 # 'forward',
 # 'Houston',
 # 'end',
 # 'FW:',
 # 'first',
 # 'dow',
 # 'contracts',
 # 'CAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgI',
 # '---------------------------',
 # 'much',
 # '----------------------',
 # 'working',
 # "don't",
 # 'each',
 # 'Mark',
 # '(713)',
 # 'since',
 # 'off',
 # 'take',
 # 'houston',
 # 'j',
 # '.75pt',
 # 'jones',
 # 'earnings',
 # 'electricity',
 # 'might',
 # 'capacity',
 # 'game',
 # '-----',
 'how',
 'Date:',
 'John',
 'day',
 'companies',
 're:',
 'shares',
 'review',
 'recipient',
 'issues',
 'under',
 'week.',
 'next',
 '-----original',
 'sent:',
 'January',
 'natural',
 'message-----',
 'Inc.',
 'year',
 'final',
 'risk',
 'It',
 'start',
 'WR',
 'AAAAyAAVAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMgAFQAAAAAAAAAAAAAAAAAAAAAAAAAAAADIABUA',
 'dynegy',
 'state',
 'employees',
 'plan',
 'debt',
 'Friday,',
 'schedule',
 'forwarded',
 'Power',
 'Mike',
 '5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm',
 '(or',
 'work',
 'see',
 'new',
 'chief',
 'percent',
 'Dow',
 'than',
 'price',
 'Fantasy',
 'all',
 'did',
 'company',
 'Thursday,',
 'Jones',
 'him',
 'get',
 'database.',
 'them',
 'group',
 'out',
 'can',
 'during',
 'time',
 '?',
 'questions',
 'stock',
 'going',
 'these',
 'Wednesday,',
 'Gas',
 'Updated',
 'one',
 'vince',
 'between',
 'following',
 'Tuesday,',
 'In',
 'because',
 'from:',
 'into',
 'more',
 'week',
 'Monday,',
 'FACE="Arial,',
 'down',
 'like',
 'Dynegy',
 'attached',
 '--',
 'back',
 'intended',
 'contract',
 'million',
 'still',
 'Cc:',
 '2000',
 'think',
 'He',
 'credit',
 'financial',
 'Energy',
 'do',
 'Please',
 'two',
 'Corp.',
 "#####'s",
 'his',
 'after',
 'may',
 'meeting',
 'when',
 'market',
 'against',
 'could',
 'November',
 'other',
 'who',
 'If',
 'RE:',
 'billion',
 'should',
 'October',
 'there',
 'let',
 'up',
 'also',
 'so',
 'call',
 'what',
 "Enron's",
 'need',
 'pm',
 'said.',
 'deal',
 'cc:',
 'you',
 '2002',
 'AM',
 'from',
 'their',
 'trading',
 'some',
 'subject:',
 'this',
 '|',
 'last',
 '-',
 'to:',
 'know',
 'which',
 'were',
 'or',
 'am',
 'gas',
 'had',
 'PM',
 'class=TD2',
 'please',
 'been',
 'any',
 '&',
 'they',
 'power',
 'about',
 'me',
 'he',
 'energy',
 'but',
 'an',
 'not',
 'i',
 '-----Original',
 'Message-----',
 'Sent:',
 'if',
 'said',
 'From:',
 'To:',
 'Subject:',
 'are',
 'has',
 'The',
 'was',
 'its',
 'as',
 'we',
 'would',
 '2001',
 'it',
 '#####',
 'by',
 'with',
 'I',
 'Enron',
 'is',
 'at',
 'have',
 'be',
 'will',
 'that',
 'for',
 'on',
 'in',
 'and',
 'a',
 'of',
 'to',
 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
 'the'] + ['=',
 '1px',
 'solid;',
 'your',
 'medium',
 'html',
 'helvetica,',
 'style=3d"border-right:',
 'align=3dmiddle',
 'face=3darial',
 'border-bottom:',
 'border-left:',
 'none;',
 'style=3d"font-size:',
 'border-top:',
 'face=3dverdana=20',
 'face=3dverdana',
 'Content-Transfer-Encoding:',
 'Content-Type:',
 'statements',
 'font-size:',
 'font-family:',
 'quoted-printable',
 'solid"=20',
 'content-type:',
 '+',
 'message',
 '{',
 'content-transfer-encoding:',
 'color:',
 'public',
 '}',
 '0cm',
 'multi-part',
 '&nbsp;',
 'border="0"',
 'arial,',
 'Adobe',
 'Helvetica,',
 'bgcolor=3d#ffffff',
 'HTML',
 'format',
 'within',
 '0px;',
 'size="2"',
 '7bit',
 'de',
 'face="arial,',
 'format.',
 'sans-serif"',
 'adobe',
 'software',
 'our',
 'Professional',
 'face=3DArial',
 'cellspacing=3d0',
 '4.0',
 'border=3D"0"',
 'XP',
 'none"=20',
 'cellpadding=3d0',
 'professional',
 'FONT-FAMILY:',
 '2005',
 'server',
 'converted',
 '2004',
 'name=3d"generator"',
 'lang=3den-us',
 'content=3d"ms',
 'font-weight:',
 'border=3d"0"',
 'text-align:',
 'online',
 'mime',
 'cellSpacing=3D0',
 'money',
 'xp',
 'e',
 '2003',
 'sans-serif;',
 'products',
 'style="font-size:',
 'version',
 'border=3d0',
 '0pt;',
 'MX',
 'face="Arial,',
 'MIME',
 'cellspacing="0"',
 'style="font-family:',
 '&#183;',
 'width="100%"',
 'collapse"',
 'cellpadding="0"',
 'exchange',
 'account',
 'class=3dmsonormal',
 'future',
 # 'COLOR:',
 # 'border=3D0',
 # 'line-height:',
 # 'style=3d"mso-ansi-language:',
 # 'face=3d"times',
 # 'style=3d"display:',
 # 'cellPadding=3D0',
 # 'Arial,',
 # 'align="center"',
 # 'PUBLIC',
 # ',',
 # '%',
 # 'style=3D"DISPLAY:',
 # 'style=3d"margin:',
 # 'bold;',
 # 'investment',
 # '$79.95',
 # 'website',
 # 'face=3d"arial,',
 # 'face=3d"arial"',
 # '(Including:',
 # 'mx',
 # 'vAlign=3Dtop',
 # 'padding-left:',
 # 'site',
 # 'charset="us-ascii"',
 # 'Windows',
 # 'pills',
 # 'class=3Dsmall',
 # 'valign=3dtop',
 # '3px',
 # '"',
 # 'height=3D18',
 # 'Office',
 # '7',
 # 'advertisement',
 # 'securities',
 # 'Photoshop',
 # '10pt;',
 # 'face=3d"verdana,',
 # 'Sans',
 # 'style="line-height:',
 # 'FONT-SIZE:',
 # 'windows',
 # 'align=center',
 # 'media',
 # 'size="1"',
 # 'newsletter',
 # 'nowrap',
 # 'prescription',
 # 'padding-right:',
 # 'security',
 # 'cellspacing=3d"0"',
 # 'forward-looking',
 # 'margin-right:',
 # '&amp;',
 # 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
 # 'email',
 # 'differ',
 # 'face=Verdana',
 # 'meaning',
 # 'registered',
 # 'shape=3D"rect"',
 # 'mail',
 # 'cellpadding=0',
 # 'information',
 # 'face=3DVerdana',
 # 'verdana,',
 # 'results',
 # 'style=3d"border-collapse:',
 # 'cellspacing=0',
 # 'style=3d"letter-spacing:',
 # 'style="FONT-SIZE:',
 # 'stop',
 # 'content=3d"mshtml',
 # 'charset="iso-8859-1"',
 # 'noWrap',
 # 'save',
 # 'align=3dright',
 # 'advice.',
 # 'normal;',
 # 'size=3d"2"',
 # 'y',
 # 'here',
 # 'solid"',
 # 'one-way,',
 # ':',
 # 'alt=3d""',
 # 'publisher',
 # '8pt"',
 # 'photoshop',
 # '10px;',
 # 'style=3d"font-weight:',
 # 'marketing',
 # 'risks',
 # 'margin-bottom:',
 # 'search',
 # 'looking',
 # 'bordercolor=3d#111111',
 # 'price:',
 # 'width=3d"100%"',
 # 'style="margin-left:',
 # '_________________________________________________________________________',
 # 'face=3d"verdana"',
 # '3px;',
 # 'Arial"',
 # 't',
 # 'verdana"',
 # '(including:',
 # '7Bit',
 # 'soft',
 # 'popular',
 # 'cellpadding=3d"0"',
 # 'x',
 # 'style="padding:',
 # 'fact',
 # 'ms',
 # 'cellSpacing=0',
 # 'style="text-align:',
 # 'align=3dleft',
 # 'visit',
 # '8bit',
 # 'Act',
 # 'color="#999999"',
 # '.',
 # '6.0',
 # 'width="1"',
 # 'cellPadding=0',
 # 'product',
 # "width='500'",
 # 'class="msonormal"',
 # "size='1'",
 # "align='center'",
 # "cellpadding='2'",
 # "height='80'",
 # "width='531'",
 # "face='arial,",
 # 'low',
 # 'size=3d2',
 # "border='0'",
 # 'expectations,',
 # 'act',
 # 'free',
 # 'china',
 # 'style=3d"border-top:',
 # 'o',
 # 'face=3darial=20',
 # 'bgcolor=3d#eee8df',
 # 'Soft',
 # '700;',
 # 'cellpadding=3D"0"',
 # '4.01',
 # 'cheaper',
 # 'yourself',
 # 'align=3Dright',
 # 'uncertainties',
 # '14px;',
 # 'none',
 # '_____________________________________________________',
 # 'involve',
 # 'cause',
 # 'color=3d#ffffff',
 # 'viagra',
 # 'align=3d"center"',
 # 'thousand',
 # 'Tabs',
 # 'events',
 # 'face=3Dverdana,arial,helvetica',
 # 'featured',
 # 'advertising',
 # 'materially',
 # 'cellspacing=3D"0"',
 # 'height=3d18',
 # '(5',
 # '$89.95',
 # 'size=5',
 # 'here:',
 # '0in',
 # 'class=3dsmall',
 # 'charset=us-ascii',
 # 'colspan=3d2',
 # '1px;',
 # 'technology',
 # 'Acrobat',
 # 'style="color:',
 # 'wish',
 # 'width=3D5',
 # 'face="MS',
 # 'style=3D"FONT-SIZE:',
 # 'charset=iso-8859-1',
 # '0px',
 # 'travel',
 # 'solutions',
 # 'size="4"',
 # 'DISC0UNT',
 # '#message',
 # 'Verdana,',
 # 'advice',
 # 'bgcolor=3d#ffff00',
 # 'Serif,',
 # '#ffffff;',
 # '|&nbsp;',
 # 'width=3D=',
 # 'assumptions',
 # 'macromedia',
 # '9pt"',
 # 'inherent',
 # 'Illustrator',
 # 'g',
 # '--=_nextpart_2rfkindysadvnqw3nerasdf',
 # 'instant',
 # 'text-decoration:',
 # '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&=',
 # 'ebay',
 # 'que',
 # '--=_nextpart_2rfkindysadvnqw3nerasdf--',
 # 'herein',
 # 'ImageReady',
 # 'face=3dimpact',
 # 'content-disposition:',
 # '35px;',
 # '100%',
 # 'background-color:',
 # 'subscribers',
 # 'u',
 # 'width=3d650',
 # 'black;',
 # 'studio',
 # 'style=3d"background-color:',
 # 'factors',
 # 'con',
 # 'quality',
 # '13px;',
 'suite']


